

paths:
  packages_csv: "data/packages.csv"
  distances_csv: "data/distances.csv"

routing:
  heuristic: "nearest_neighbor"

hub:
  street_address: "1 Start Way"
  city: "Salt Lake City"
  state: "UT"
  zip_code: "12345"
